---
apiVersion: v1
kind: Namespace
metadata:
  name: netflz2.2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflz2.2
  namespace: netflz2.2
  labels:
    app: netflz2.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflz2.2
  template:
    metadata:
      labels:
        app: netflz2.2
    spec:
      containers:
        - name: netflz2.2
          image: limkel/netflz:2.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflz2.2
  namespace: netflz2.2
  labels:
    app: netflz2.2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: netflz2.2
