name: FortressIT Consult Inc. 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade apt packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Install necessary packages
        run: |
          sudo apt install -y npm

     
      - name: Build Docker image
        run: docker build -f Dockerfile2 -t limkel/netflx:2.0 .

      - name: Run security scans
        run: |
          ./trivy_0.20.0_Linux-64bit/trivy limkel/netflx:2.0
          dockle limkel/netflx:2.0
          ./dependency-check/bin/dependency-check.sh -d . -s limkel/netflx:2.0
