name: FortressIT Consult Inc.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '27 7 * * 6'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upgrade apt packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: 'docker.io/limkel/netflx:2.0'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Build Docker image
        run: docker build -f Dockerfile2 -t limkel/netflx:2.0 .

      - name: Run security scans
        run: |
          ./trivy_0.20.0_Linux-64bit/trivy limkel/netflx:2.0
          dockle limkel/netflx:2.0
          ./dependency-check/bin/dependency-check.sh -d . -s limkel/netflx:2.0
